"""Initial migration

Revision ID: b66e561e83b9
Revises: 
Create Date: 2026-04-23 14:02:46.330196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b66e561e83b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'AGENT', name='userrole'), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index('idx_user_role', 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('crop_type', sa.String(), nullable=False),
    sa.Column('planting_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_stage', sa.Enum('PLANTED', 'GERMINATION', 'VEGETATIVE', 'FLOWERING', 'MATURE', 'HARVESTED', name='fieldstage'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_field_created_by', 'fields', ['created_by'], unique=False)
    op.create_index('idx_field_crop_stage', 'fields', ['crop_type', 'current_stage'], unique=False)
    op.create_index('idx_field_planting_date', 'fields', ['planting_date'], unique=False)
    op.create_index(op.f('ix_fields_crop_type'), 'fields', ['crop_type'], unique=False)
    op.create_index(op.f('ix_fields_id'), 'fields', ['id'], unique=False)
    op.create_index(op.f('ix_fields_name'), 'fields', ['name'], unique=False)
    op.create_index(op.f('ix_fields_planting_date'), 'fields', ['planting_date'], unique=False)
    op.create_table('field_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_id'),
    sa.UniqueConstraint('field_id', name='uq_field_assignment')
    )
    op.create_index('idx_assignment_agent', 'field_assignments', ['agent_id'], unique=False)
    op.create_index('idx_assignment_field', 'field_assignments', ['field_id'], unique=False)
    op.create_index(op.f('ix_field_assignments_id'), 'field_assignments', ['id'], unique=False)
    op.create_table('field_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('new_stage', sa.Enum('PLANTED', 'GERMINATION', 'VEGETATIVE', 'FLOWERING', 'MATURE', 'HARVESTED', name='fieldstage'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_update_agent', 'field_updates', ['agent_id'], unique=False)
    op.create_index('idx_update_field_created', 'field_updates', ['field_id', 'created_at'], unique=False)
    op.create_index('idx_update_stage', 'field_updates', ['new_stage'], unique=False)
    op.create_index(op.f('ix_field_updates_agent_id'), 'field_updates', ['agent_id'], unique=False)
    op.create_index(op.f('ix_field_updates_field_id'), 'field_updates', ['field_id'], unique=False)
    op.create_index(op.f('ix_field_updates_id'), 'field_updates', ['id'], unique=False)
    op.create_table('ai_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('update_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['update_id'], ['field_updates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('update_id')
    )
    op.create_index('idx_alert_type_created', 'ai_alerts', ['alert_type', 'created_at'], unique=False)
    op.create_index('idx_alert_update', 'ai_alerts', ['update_id'], unique=False)
    op.create_index(op.f('ix_ai_alerts_id'), 'ai_alerts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_alerts_id'), table_name='ai_alerts')
    op.drop_index('idx_alert_update', table_name='ai_alerts')
    op.drop_index('idx_alert_type_created', table_name='ai_alerts')
    op.drop_table('ai_alerts')
    op.drop_index(op.f('ix_field_updates_id'), table_name='field_updates')
    op.drop_index(op.f('ix_field_updates_field_id'), table_name='field_updates')
    op.drop_index(op.f('ix_field_updates_agent_id'), table_name='field_updates')
    op.drop_index('idx_update_stage', table_name='field_updates')
    op.drop_index('idx_update_field_created', table_name='field_updates')
    op.drop_index('idx_update_agent', table_name='field_updates')
    op.drop_table('field_updates')
    op.drop_index(op.f('ix_field_assignments_id'), table_name='field_assignments')
    op.drop_index('idx_assignment_field', table_name='field_assignments')
    op.drop_index('idx_assignment_agent', table_name='field_assignments')
    op.drop_table('field_assignments')
    op.drop_index(op.f('ix_fields_planting_date'), table_name='fields')
    op.drop_index(op.f('ix_fields_name'), table_name='fields')
    op.drop_index(op.f('ix_fields_id'), table_name='fields')
    op.drop_index(op.f('ix_fields_crop_type'), table_name='fields')
    op.drop_index('idx_field_planting_date', table_name='fields')
    op.drop_index('idx_field_crop_stage', table_name='fields')
    op.drop_index('idx_field_created_by', table_name='fields')
    op.drop_table('fields')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_role', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_index('idx_user_active', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
